"""
Evidence, Citation, and Alert models.

These three models form the "trust layer" of PathogenIQ:
  - Citation: links any claim back to a source Document
  - EvidenceScore: quantifies how well-supported a claim is
  - Alert: human-facing notification about significant events

Why is this so important?
  LLMs hallucinate. A model might confidently state "Drug X has 85% efficacy
  against Pathogen Y" — and be completely wrong. The only way to build a
  trustworthy biomedical AI is to:
    1. Require every claim to cite a source Document
    2. Score the quality of the evidence
    3. Surface low-confidence claims prominently to human reviewers
"""

import enum
import uuid

from sqlalchemy import Enum, Float, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDMixin


class EvidenceLevel(str, enum.Enum):
    """
    Oxford Centre for Evidence-Based Medicine levels, simplified.

    This maps roughly to:
      SYSTEMATIC_REVIEW: Level 1a — meta-analyses of RCTs
      RCT:               Level 1b — individual RCTs
      COHORT_STUDY:      Level 2 — prospective cohort studies
      CASE_CONTROL:      Level 3 — retrospective case-control
      CASE_SERIES:       Level 4 — case reports, case series
      EXPERT_OPINION:    Level 5 — editorials, expert opinion
      AI_INFERRED:       Not in Oxford levels — AI synthesis, lowest trust
    """
    SYSTEMATIC_REVIEW = "systematic_review"
    RCT = "rct"
    COHORT_STUDY = "cohort_study"
    CASE_CONTROL = "case_control"
    CASE_SERIES = "case_series"
    EXPERT_OPINION = "expert_opinion"
    AI_INFERRED = "ai_inferred"         # generated by an AI agent — always requires human review


class EvidenceScore(UUIDMixin, TimestampMixin, Base):
    """
    Quantified evidence quality for a specific claim about an outbreak.

    confidence_score (0.0–1.0): composite score calculated by the Verifier Agent.
    evidence_level: qualitative category based on the source study type.
    citation_count: how many independent sources support this claim.
    conflicting_evidence: are there papers that contradict this claim?

    These fields feed the risk briefing generated by the Atlas Agent.
    """

    __tablename__ = "evidence_scores"

    outbreak_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("outbreaks.id", ondelete="CASCADE"),
        nullable=False,
    )
    claim_text: Mapped[str] = mapped_column(Text, nullable=False)  # the specific claim being scored
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False)
    evidence_level: Mapped[EvidenceLevel] = mapped_column(
        Enum(EvidenceLevel, name="evidence_level_enum"),
        nullable=False,
    )
    citation_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    conflicting_evidence: Mapped[bool] = mapped_column(default=False, nullable=False)
    verifier_notes: Mapped[str | None] = mapped_column(Text)

    outbreak: Mapped["Outbreak"] = relationship("Outbreak", back_populates="evidence_scores")  # noqa: F821

    __table_args__ = (
        Index("ix_evidence_scores_outbreak_id", "outbreak_id"),
    )


class Citation(UUIDMixin, TimestampMixin, Base):
    """
    Links a specific claim (text) to the Document that supports it.

    This is the anti-hallucination mechanism: every AI-generated claim
    must be grounded in a real Document. If the Verifier Agent cannot
    find a Document that supports a claim, that claim is flagged.

    excerpt: the exact text span from the Document that was used.
    page_or_section: where in the document (for long PDFs or reports).
    relevance_score: how relevant is this citation to the claim (0.0–1.0)?
    """

    __tablename__ = "citations"

    document_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    claim_text: Mapped[str] = mapped_column(Text, nullable=False)
    excerpt: Mapped[str | None] = mapped_column(Text)
    page_or_section: Mapped[str | None] = mapped_column(String(256))
    relevance_score: Mapped[float | None] = mapped_column(Float)
    cited_by_agent: Mapped[str | None] = mapped_column(String(128))  # "scholar", "verifier", etc.

    document: Mapped["Document"] = relationship("Document", back_populates="citations")  # noqa: F821

    __table_args__ = (
        Index("ix_citations_document_id", "document_id"),
    )


class AlertSeverity(str, enum.Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class Alert(UUIDMixin, TimestampMixin, Base):
    """
    A human-facing notification about an outbreak event.

    Alerts are generated by the Atlas Agent (executive synthesis) after
    all other agents have processed a new outbreak or significant update.

    acknowledged: a human reviewer has seen this alert.
    review_notes: what the reviewer decided.

    Why store acknowledgement in the DB (not just the frontend)?
      - Audit trail: you need to know who reviewed what, when.
      - In a clinical or public health setting, unacknowledged critical alerts
        may need escalation logic (e.g., page an on-call epidemiologist).
    """

    __tablename__ = "alerts"

    outbreak_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("outbreaks.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(1024), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity, name="alert_severity_enum"),
        nullable=False,
    )
    acknowledged: Mapped[bool] = mapped_column(default=False, nullable=False)
    acknowledged_by: Mapped[str | None] = mapped_column(String(256))
    review_notes: Mapped[str | None] = mapped_column(Text)
    generated_by_model: Mapped[str | None] = mapped_column(String(128))

    outbreak: Mapped["Outbreak"] = relationship("Outbreak", back_populates="alerts")  # noqa: F821

    __table_args__ = (
        Index("ix_alerts_outbreak_id", "outbreak_id"),
        Index(
            "ix_alerts_unacknowledged_critical",
            "severity",
            "acknowledged",
            postgresql_where="acknowledged = false",
        ),
    )
